/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppOperatorsRouteImport } from './routes/_app.operators'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCloudRouteImport } from './routes/_app.cloud'
import { Route as AppReposIndexRouteImport } from './routes/_app.repos.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppReposAddRouteImport } from './routes/_app.repos.add'
import { Route as AppReposRepoNameRouteImport } from './routes/_app.repos.$repoName'
import { Route as AppProjectsNameRouteImport } from './routes/_app.projects.$name'
import { Route as AppCloudMachinesRouteImport } from './routes/_app.cloud.machines'
import { Route as AppCloudJobsRouteImport } from './routes/_app.cloud.jobs'
import { Route as AppCloudBindingsRouteImport } from './routes/_app.cloud.bindings'
import { Route as AppProjectsNamePilotRunsRouteImport } from './routes/_app.projects.$name_.pilot-runs'
import { Route as AppRunsSlugIssueTsRouteImport } from './routes/_app.runs.$slug.$issue.$ts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorsRoute = AppOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCloudRoute = AppCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AppRoute,
} as any)
const AppReposIndexRoute = AppReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppReposAddRoute = AppReposAddRouteImport.update({
  id: '/repos/add',
  path: '/repos/add',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRepoNameRoute = AppReposRepoNameRouteImport.update({
  id: '/repos/$repoName',
  path: '/repos/$repoName',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNameRoute = AppProjectsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppCloudMachinesRoute = AppCloudMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AppCloudRoute,
} as any)
const AppCloudJobsRoute = AppCloudJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppCloudRoute,
} as any)
const AppCloudBindingsRoute = AppCloudBindingsRouteImport.update({
  id: '/bindings',
  path: '/bindings',
  getParentRoute: () => AppCloudRoute,
} as any)
const AppProjectsNamePilotRunsRoute =
  AppProjectsNamePilotRunsRouteImport.update({
    id: '/$name_/pilot-runs',
    path: '/$name/pilot-runs',
    getParentRoute: () => AppProjectsRoute,
  } as any)
const AppRunsSlugIssueTsRoute = AppRunsSlugIssueTsRouteImport.update({
  id: '/runs/$slug/$issue/$ts',
  path: '/runs/$slug/$issue/$ts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloud': typeof AppCloudRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/operators': typeof AppOperatorsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/cloud/bindings': typeof AppCloudBindingsRoute
  '/cloud/jobs': typeof AppCloudJobsRoute
  '/cloud/machines': typeof AppCloudMachinesRoute
  '/projects/$name': typeof AppProjectsNameRoute
  '/repos/$repoName': typeof AppReposRepoNameRoute
  '/repos/add': typeof AppReposAddRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/repos/': typeof AppReposIndexRoute
  '/projects/$name/pilot-runs': typeof AppProjectsNamePilotRunsRoute
  '/runs/$slug/$issue/$ts': typeof AppRunsSlugIssueTsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloud': typeof AppCloudRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/operators': typeof AppOperatorsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/cloud/bindings': typeof AppCloudBindingsRoute
  '/cloud/jobs': typeof AppCloudJobsRoute
  '/cloud/machines': typeof AppCloudMachinesRoute
  '/projects/$name': typeof AppProjectsNameRoute
  '/repos/$repoName': typeof AppReposRepoNameRoute
  '/repos/add': typeof AppReposAddRoute
  '/projects': typeof AppProjectsIndexRoute
  '/repos': typeof AppReposIndexRoute
  '/projects/$name/pilot-runs': typeof AppProjectsNamePilotRunsRoute
  '/runs/$slug/$issue/$ts': typeof AppRunsSlugIssueTsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/cloud': typeof AppCloudRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/operators': typeof AppOperatorsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/cloud/bindings': typeof AppCloudBindingsRoute
  '/_app/cloud/jobs': typeof AppCloudJobsRoute
  '/_app/cloud/machines': typeof AppCloudMachinesRoute
  '/_app/projects/$name': typeof AppProjectsNameRoute
  '/_app/repos/$repoName': typeof AppReposRepoNameRoute
  '/_app/repos/add': typeof AppReposAddRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/repos/': typeof AppReposIndexRoute
  '/_app/projects/$name_/pilot-runs': typeof AppProjectsNamePilotRunsRoute
  '/_app/runs/$slug/$issue/$ts': typeof AppRunsSlugIssueTsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloud'
    | '/dashboard'
    | '/operators'
    | '/projects'
    | '/settings'
    | '/usage'
    | '/cloud/bindings'
    | '/cloud/jobs'
    | '/cloud/machines'
    | '/projects/$name'
    | '/repos/$repoName'
    | '/repos/add'
    | '/projects/'
    | '/repos/'
    | '/projects/$name/pilot-runs'
    | '/runs/$slug/$issue/$ts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cloud'
    | '/dashboard'
    | '/operators'
    | '/settings'
    | '/usage'
    | '/cloud/bindings'
    | '/cloud/jobs'
    | '/cloud/machines'
    | '/projects/$name'
    | '/repos/$repoName'
    | '/repos/add'
    | '/projects'
    | '/repos'
    | '/projects/$name/pilot-runs'
    | '/runs/$slug/$issue/$ts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/cloud'
    | '/_app/dashboard'
    | '/_app/operators'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/usage'
    | '/_app/cloud/bindings'
    | '/_app/cloud/jobs'
    | '/_app/cloud/machines'
    | '/_app/projects/$name'
    | '/_app/repos/$repoName'
    | '/_app/repos/add'
    | '/_app/projects/'
    | '/_app/repos/'
    | '/_app/projects/$name_/pilot-runs'
    | '/_app/runs/$slug/$issue/$ts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operators': {
      id: '/_app/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AppOperatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cloud': {
      id: '/_app/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AppCloudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos/': {
      id: '/_app/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof AppReposIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/repos/add': {
      id: '/_app/repos/add'
      path: '/repos/add'
      fullPath: '/repos/add'
      preLoaderRoute: typeof AppReposAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos/$repoName': {
      id: '/_app/repos/$repoName'
      path: '/repos/$repoName'
      fullPath: '/repos/$repoName'
      preLoaderRoute: typeof AppReposRepoNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$name': {
      id: '/_app/projects/$name'
      path: '/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof AppProjectsNameRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/cloud/machines': {
      id: '/_app/cloud/machines'
      path: '/machines'
      fullPath: '/cloud/machines'
      preLoaderRoute: typeof AppCloudMachinesRouteImport
      parentRoute: typeof AppCloudRoute
    }
    '/_app/cloud/jobs': {
      id: '/_app/cloud/jobs'
      path: '/jobs'
      fullPath: '/cloud/jobs'
      preLoaderRoute: typeof AppCloudJobsRouteImport
      parentRoute: typeof AppCloudRoute
    }
    '/_app/cloud/bindings': {
      id: '/_app/cloud/bindings'
      path: '/bindings'
      fullPath: '/cloud/bindings'
      preLoaderRoute: typeof AppCloudBindingsRouteImport
      parentRoute: typeof AppCloudRoute
    }
    '/_app/projects/$name_/pilot-runs': {
      id: '/_app/projects/$name_/pilot-runs'
      path: '/$name/pilot-runs'
      fullPath: '/projects/$name/pilot-runs'
      preLoaderRoute: typeof AppProjectsNamePilotRunsRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/runs/$slug/$issue/$ts': {
      id: '/_app/runs/$slug/$issue/$ts'
      path: '/runs/$slug/$issue/$ts'
      fullPath: '/runs/$slug/$issue/$ts'
      preLoaderRoute: typeof AppRunsSlugIssueTsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCloudRouteChildren {
  AppCloudBindingsRoute: typeof AppCloudBindingsRoute
  AppCloudJobsRoute: typeof AppCloudJobsRoute
  AppCloudMachinesRoute: typeof AppCloudMachinesRoute
}

const AppCloudRouteChildren: AppCloudRouteChildren = {
  AppCloudBindingsRoute: AppCloudBindingsRoute,
  AppCloudJobsRoute: AppCloudJobsRoute,
  AppCloudMachinesRoute: AppCloudMachinesRoute,
}

const AppCloudRouteWithChildren = AppCloudRoute._addFileChildren(
  AppCloudRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsNameRoute: typeof AppProjectsNameRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsNamePilotRunsRoute: typeof AppProjectsNamePilotRunsRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsNameRoute: AppProjectsNameRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsNamePilotRunsRoute: AppProjectsNamePilotRunsRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppCloudRoute: typeof AppCloudRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOperatorsRoute: typeof AppOperatorsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppReposRepoNameRoute: typeof AppReposRepoNameRoute
  AppReposAddRoute: typeof AppReposAddRoute
  AppReposIndexRoute: typeof AppReposIndexRoute
  AppRunsSlugIssueTsRoute: typeof AppRunsSlugIssueTsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCloudRoute: AppCloudRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOperatorsRoute: AppOperatorsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppReposRepoNameRoute: AppReposRepoNameRoute,
  AppReposAddRoute: AppReposAddRoute,
  AppReposIndexRoute: AppReposIndexRoute,
  AppRunsSlugIssueTsRoute: AppRunsSlugIssueTsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
