/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppOperatorsRouteImport } from './routes/_app.operators'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppReposIndexRouteImport } from './routes/_app.repos.index'
import { Route as AppReposRepoNameRouteImport } from './routes/_app.repos.$repoName'
import { Route as AppRunsSlugIssueTsRouteImport } from './routes/_app.runs.$slug.$issue.$ts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorsRoute = AppOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppReposIndexRoute = AppReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRepoNameRoute = AppReposRepoNameRouteImport.update({
  id: '/repos/$repoName',
  path: '/repos/$repoName',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsSlugIssueTsRoute = AppRunsSlugIssueTsRouteImport.update({
  id: '/runs/$slug/$issue/$ts',
  path: '/runs/$slug/$issue/$ts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/operators': typeof AppOperatorsRoute
  '/usage': typeof AppUsageRoute
  '/repos/$repoName': typeof AppReposRepoNameRoute
  '/repos/': typeof AppReposIndexRoute
  '/runs/$slug/$issue/$ts': typeof AppRunsSlugIssueTsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/operators': typeof AppOperatorsRoute
  '/usage': typeof AppUsageRoute
  '/repos/$repoName': typeof AppReposRepoNameRoute
  '/repos': typeof AppReposIndexRoute
  '/runs/$slug/$issue/$ts': typeof AppRunsSlugIssueTsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/operators': typeof AppOperatorsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/repos/$repoName': typeof AppReposRepoNameRoute
  '/_app/repos/': typeof AppReposIndexRoute
  '/_app/runs/$slug/$issue/$ts': typeof AppRunsSlugIssueTsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/operators'
    | '/usage'
    | '/repos/$repoName'
    | '/repos/'
    | '/runs/$slug/$issue/$ts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/operators'
    | '/usage'
    | '/repos/$repoName'
    | '/repos'
    | '/runs/$slug/$issue/$ts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/operators'
    | '/_app/usage'
    | '/_app/repos/$repoName'
    | '/_app/repos/'
    | '/_app/runs/$slug/$issue/$ts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operators': {
      id: '/_app/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AppOperatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos/': {
      id: '/_app/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof AppReposIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos/$repoName': {
      id: '/_app/repos/$repoName'
      path: '/repos/$repoName'
      fullPath: '/repos/$repoName'
      preLoaderRoute: typeof AppReposRepoNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$slug/$issue/$ts': {
      id: '/_app/runs/$slug/$issue/$ts'
      path: '/runs/$slug/$issue/$ts'
      fullPath: '/runs/$slug/$issue/$ts'
      preLoaderRoute: typeof AppRunsSlugIssueTsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOperatorsRoute: typeof AppOperatorsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppReposRepoNameRoute: typeof AppReposRepoNameRoute
  AppReposIndexRoute: typeof AppReposIndexRoute
  AppRunsSlugIssueTsRoute: typeof AppRunsSlugIssueTsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOperatorsRoute: AppOperatorsRoute,
  AppUsageRoute: AppUsageRoute,
  AppReposRepoNameRoute: AppReposRepoNameRoute,
  AppReposIndexRoute: AppReposIndexRoute,
  AppRunsSlugIssueTsRoute: AppRunsSlugIssueTsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
